### ISSUE TITLE
can't run the app after creating the project

### ISSUE THREAD

**Issue by bobwatcherx** [pyfyre/pyfyre#36]
my error log
```
[E 230529 11:49:55 web:1871] Uncaught exception GET / (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:5500', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1763, in _execute
        result = self.prepare()
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3138, in prepare
        self.fallback(self.request)
      File "/usr/local/lib/python3.10/dist-packages/livereload/server.py", line 133, in __call__
        WSGIContainer.environ(request), start_response)
    TypeError: WSGIContainer.environ() missing 1 required positional argument: 'request'
[E 230529 11:49:55 web:2344] 500 GET / (127.0.0.1) 63.49ms
[E 230529 11:49:56 web:1871] Uncaught exception GET /favicon.ico (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:5500', method='GET', uri='/favicon.ico', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1763, in _execute
        result = self.prepare()
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3138, in prepare
        self.fallback(self.request)
      File "/usr/local/lib/python3.10/dist-packages/livereload/server.py", line 133, in __call__
        WSGIContainer.environ(request), start_response)
    TypeError: WSGIContainer.environ() missing 1 required positional argument: 'request'
[E 230529 11:49:56 web:2344] 500 GET /favicon.ico (127.0.0.1) 1.78ms
```

**Comment by jabezborja** [comment]
Hello there, can you provide a steps to reproduce this error? I have tried creating a new project with PyFyre from its latest version from PIP and it's working fine.

**Comment by nacho00112** [comment]
Until the official livereload get updated you can install this unofficial version with the bugs fixed:
```bash
pip install https://github.com/nacho00112/pyfyre/archive/refs/heads/master.zip
```

**Comment by bobwatcherx** [comment]
```
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/clisd/clisd.py/my-cool-app# pip install https://github.com/nacho00112/pyfyre/archive/refs/heads/master.zip
Collecting https://github.com/nacho00112/pyfyre/archive/refs/heads/master.zip
  Using cached https://github.com/nacho00112/pyfyre/archive/refs/heads/master.zip
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in pyfyre setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
          https://github.com/nacho00112/python-livereload/archive/refs/heads/master.zip
               ^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by bobwatcherx** [comment]
i use this python version
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/clisd/clisd.py/my-cool-app# python3 --version
Python 3.10.6

**Comment by bobwatcherx** [comment]
i still get error .  while installing pip install pyfyre
```
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/clisd/clisd.py/my-cool-app# pyfyre run
Generating package src
adding settings package False
adding index package False
adding pyfyre.router package False
adding pyfyre.utils package False
adding pyfyre.states package False
adding pyfyre.exceptions package False
adding pyfyre.styles package False
adding pyfyre.events package False
adding pyfyre package True
adding pyfyre.nodes.buttons package False
adding pyfyre.nodes.base package False
adding pyfyre.nodes.inputs package False
adding pyfyre.nodes.widgets package False
adding pyfyre.nodes.links package False
adding pyfyre.nodes package True
adding pyfyre.nodes.lists package False
adding pyfyre.nodes.futures package False
adding pyfyre.presets.loading package False
adding pyfyre.presets package True
adding pyfyre.presets.errors package False
20 files
done
[I 230729 16:22:15 server:335] Serving on http://localhost:5500
[I 230729 16:22:15 handlers:62] Start watching changes
[E 230729 16:22:18 web:1871] Uncaught exception GET / (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:5500', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1763, in _execute
        result = self.prepare()
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3138, in prepare
        self.fallback(self.request)
      File "/usr/local/lib/python3.10/dist-packages/livereload/server.py", line 133, in __call__
        WSGIContainer.environ(request), start_response)
    TypeError: WSGIContainer.environ() missing 1 required positional argument: 'request'
[E 230729 16:22:18 web:2344] 500 GET / (127.0.0.1) 5.68ms

```

**Comment by jgcb00** [comment]
Hi, I have exactly the same error, any idea ?
